### ISSUE TITLE
Error preparing Blob/File data to be stored in object store

### ISSUE THREAD

**Issue by dmitrizzle** [localForage/localForage#834]
This is happening in iOS Safari 11.3.1
<img width="1001" alt="screen shot 2018-07-09 at 9 11 52 pm" src="https://user-images.githubusercontent.com/8587882/42455742-44b8312e-83bd-11e8-91df-ff0d3075f97b.png">
<img width="1001" alt="screen shot 2018-07-09 at 9 11 35 pm" src="https://user-images.githubusercontent.com/8587882/42455747-46cb4cbc-83bd-11e8-8e40-af4bbc3e004a.png">

Wondering if this is related: https://github.com/pouchdb/pouchdb/issues/7057

**Comment by dmitrizzle** [comment]
Tried downgrading `localforage` to earlier versions to no avail. This must be the iOS Safari issue, the newest version of which has issues storing blobs for some reason. They are empty objects in the database:
<img width="826" alt="screen shot 2018-07-31 at 11 03 42 pm" src="https://user-images.githubusercontent.com/8587882/43503925-31d93458-9516-11e8-8b14-bc99346482a4.png">

**Comment by dmitrizzle** [comment]
OK so the reason this has been happening is because on **iOS `File` blobs can no longer be stored.**
To solve this when this comes to storing images, specifically (as is in my case) they have to be converted to strings first. Below is the quick function I used to do that in my project:

```javascript
const fileToBase64 = file => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.addEventListener("load", () => {
      resolve(reader.result);
    });
    reader.addEventListener("error", error => {
      reject(error);
    });
  });
};
```
then
```javascript
const key = "random_key_string"
fileToBase64(file).then(string => localForage.setItem(key, string));
```

This issue is a regression on iOS but I thought it'd be useful to add this solution, should anyone else experience this problem with `localForage` or any other browser DB engines.

**Comment by tofumatt** [comment]
Hmm, so we should probably be handling this ourselves given it's a regression. I'll reopen this as it's a legit bug (and a regression).

**Comment by jakearchibald** [comment]
I've filed https://bugs.webkit.org/show_bug.cgi?id=188438.

**Comment by sebvie** [comment]
the webkit bug seems to be fixed now

**Comment by hackingbeauty** [comment]
@sebvie it doesn't appear to be fixed.  I'm still getting the error on Safari on iOS.

**Comment by tofumatt** [comment]
I don't think that fix has been released yet, so the bug is likely still there. I don't think fixes to WebKit core get included into Safari and then into iOS that quickly.

**Comment by dfibuch** [comment]
That's good to know in a way, means it hasn't broken again on iOS 12. Is there any way to find out when it goes in?

**Comment by tofumatt** [comment]
I’m honestly not sure, best bet would be to check the next beta of iOS and see if it works (or maybe check the release notes for the version of WebKit used).

- Matt (Sent from mobile)

**Comment by nsutherland** [comment]
I believe Apple has fixed the issue. However, an empty file shell will still throw the error. new FormData(form) creates a file for any file input with a name attribute whether or not it has a file(s)
